export { default as hablaWhiteLogo } from './Regular_Logo_black.png';
export { default as hablaBlackLogo } from './Regular_Logo_white.png';
export { default as hablaBlackLogoIcon } from './HABLA-logo-icon.png';
export { default as hablaFullBlackLogoIcon } from './HABLA-logo-icon-black-transparent.png';
export { default as hablaGrayLogo } from './HABLA-logo-small.png';
export { default as hablaLogoAvatar } from './habla-icon-color-in-transparent.png';
export { default as RobotHumanHandshake } from './robot-human-hand-shake.jpg';
export { default as boxLogo } from './box-logo.png';
export { default as notificationIcon } from './habla-icon-color-in-transparent.png';
export { default as googleDriveLogo } from './drive-logo.png';
export { default as googleDriveExtraLogo } from './drive-logo-extra.png';
export { default as gSuiteLogo } from './gsuite-logo.png';
export { default as sharepointLogo } from './sharepoint-logo.png';
export { default as office365Logo } from './office365-logo.png';
export { default as salesforceLogo } from './salesforce-logo.png';
export { default as dropboxLogo } from './dropbox-logo.png';
export { default as exchangeLogo } from './exchange-logo.png';
export { default as oneDriveLogo } from './onedrive-logo.png';
export { default as oneDriveExtraLogo } from './onedrive-logo-extra.png';
export { default as slackLogo } from './slack-logo.png';
export { default as trelloLogo } from './trello-logo.png';
export { default as jiraLogo } from './jira-logo.png';
export { default as gitHubLogo } from './github-logo.png';
export { default as adobeLogo } from './creativecloud-logo.png';
export { default as ibmConnectionsLogo } from './ibmconnections-logo.png';

// Corporate Knowledge Graphs placeholders
export { default as CKGthumb1 } from './plant-uptime-line-string-thumb.png';
export { default as CKGthumb2 } from './plant-daily-uptime.png';
export { default as CKGthumb3 } from './plant-uptime-week-thumb.png';
export { default as CKGthumb4 } from './downtime-reasons-thumb.png';
export { default as CKGthumb5 } from './downtime-comparison-thumb.png';

/* eslint-disable camelcase */

// export { default as fileType_AfterEffects } from './file-types/after-effects.png';
export { default as fileType_AI } from './file-types/ai.png'; //
export { default as fileType_Audition } from './file-types/audition.png';
export { default as fileType_AVI } from './file-types/avi.png';
export { default as fileType_Bridge } from './file-types/bridge.png';
export { default as fileType_CSS } from './file-types/css.png';
export { default as fileType_CSV } from './file-types/csv.png';
export { default as fileType_DBF } from './file-types/dbf.png';
export { default as fileType_DOC } from './file-types/doc.png';
export { default as fileType_Dreamweaver } from './file-types/dreamweaver.png';
export { default as fileType_DWG } from './file-types/dwg.png';
export { default as fileType_EXE } from './file-types/exe.png';
export { default as fileType_File } from './file-types/file.png';
export { default as fileType_Fireworks } from './file-types/fireworks.png';
export { default as fileType_FLA } from './file-types/fla.png';
export { default as fileType_Flash } from './file-types/flash.png';
export { default as fileType_HTML } from './file-types/html.png';
export { default as fileType_Illustrator } from './file-types/illustrator.png';
export { default as fileType_Indesign } from './file-types/indesign.png';
export { default as fileType_ISO } from './file-types/iso.png';
export { default as fileType_Javascript } from './file-types/javascript.png';
export { default as fileType_JPG } from './file-types/jpg.png';
export { default as fileType_JS } from './file-types/js.png';
// export { default as fileType_JSONFile } from './file-types/json-file.png';
export { default as fileType_jSON } from './file-types/json-file.png';
export { default as fileType_MP3 } from './file-types/mp3.png';
export { default as fileType_MP4 } from './file-types/mp4.png';
export { default as fileType_PDF } from './file-types/pdf.png';
export { default as fileType_Photoshop } from './file-types/photoshop.png';
export { default as fileType_PNG } from './file-types/png.png';
export { default as fileType_PPT } from './file-types/ppt.png';
export { default as fileType_Prelude } from './file-types/prelude.png';
export { default as fileType_Premiere } from './file-types/premiere.png';
export { default as fileType_PSD } from './file-types/psd.png';
export { default as fileType_RTF } from './file-types/rtf.png';
export { default as fileType_Search } from './file-types/search.png';
export { default as fileType_SVG } from './file-types/svg.png';
export { default as fileType_TXT } from './file-types/txt.png';
export { default as fileType_XLS } from './file-types/xls.png';
export { default as fileType_XML } from './file-types/xml.png';
export { default as fileType_ZIP } from './file-types/zip.png';
